kind: pipeline
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
    registry: 192.168.10.200:5000
    repo: "192.168.10.200:5000/${DRONE_REPO_NAME}"
    insecure: true

---
kind: secret
name: kubernetes_cert
get:
  path: drone-kubernetes
  name: cert
---
kind: secret
name: kubernetes_token
get:
  path: drone-kubernetes
  name: token
