apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- mariadb.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dolibarr
  spec:
    template:
      spec:
        containers:
        - name: dolibarr
          env:
          - name: DOLI_DB_HOST
            value: "mariadb"
          - name: DOLI_DB_PORT
            value: "3306"
          - name: DOLI_DB_TYPE
            value: "mysqli"
          - name: DOLI_DB_USER
            value: "dolibarr"
          - name: DOLI_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: dolibarr-mariadb
