---
apiVersion: v1
kind: Secret
data:
  password: ZG9saWJhcnI=
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: dolibarr-mariadb
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: dolibarr-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dolibarr-dolibarr
      app.kubernetes.io/name: dolibarr
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dolibarr-dolibarr
        app.kubernetes.io/name: dolibarr
        app.kubernetes.io/component: database
    spec:
      volumes:
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
      - name: storage-volume
        persistentVolumeClaim:
          claimName: dolibarr-mariadb
      containers:
      - name: maria
        image: mariadb:10
        volumeMounts:
          - name: storage-volume
            mountPath: /var/lib/mysql
          - name: tmp
            mountPath: /tmp
          - name: run
            mountPath: /run/mysqld
        securityContext:
          runAsGroup: 999
          runAsNonRoot: true
          runAsUser: 999
          readOnlyRootFilesystem: true
        ports:
        - name: sql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MARIADB_MYSQL_LOCALHOST_USER
          value: "true"
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: dolibarr
        - name: MYSQL_USER
          value: "dolibarr"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dolibarr-mariadb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: mariadb
spec:
  ports:
  - name: sql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  type: ClusterIP
