apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- db.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dolibarr
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: dolibarr
          env:
          - name: DOLI_DB_HOST
            value: "dolibarr-dolibarr"
          - name: DOLI_DB_PORT
            value: "5432"
          - name: DOLI_DB_TYPE
            value: "pgsql"
          - name: DOLI_DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: dolibarr.dolibarr-dolibarr.credentials.postgresql.acid.zalan.do
          - name: DOLI_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: dolibarr.dolibarr-dolibarr.credentials.postgresql.acid.zalan.do
