---
apiVersion: v1
kind: Secret
data:
  password: ZG9saWJhcnI=
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: dolibarr-pg
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: dolibarr-pg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dolibarr-dolibarr
      app.kubernetes.io/name: dolibarr
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dolibarr-dolibarr
        app.kubernetes.io/name: dolibarr
        app.kubernetes.io/component: database
    spec:
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: dolibarr-pg
      containers:
      - name: pg
        image: postgres:12-alpine
        volumeMounts:
          - name: storage-volume
            mountPath: /var/lib/postgresql
        ports:
        - name: sql
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: dolibarr
        - name: POSTGRES_USER
          value: dolibarr
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dolibarr-pg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  name: postgres
spec:
  ports:
  - name: sql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: dolibarr-dolibarr
    app.kubernetes.io/name: dolibarr
    app.kubernetes.io/component: database
  type: ClusterIP
